Vagrant.configure("2") do |config|
  
  config.vm.define :controlPlane do |controlPlane|
    controlPlane.vm.box = "ubuntu/bionic64"
    controlPlane.vm.hostname = "control-plane"
    controlPlane.vm.network "private_network", type: "dhcp"

    controlPlane.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end

    controlPlane.vm.provision :shell, path: "k8s_install.sh"
    controlPlane.vm.provision :file, source: "./manifests", destination: "./manifests"
  end

  workers_machines_names = ["worker1", "worker2"]

  workers_machines_names.each do |machine_name|
    config.vm.define machine_name do |config|
      config.vm.box = "ubuntu/bionic64"
      config.vm.hostname = machine_name
      config.vm.network "private_network", type: "dhcp"
  
      config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
  
      config.vm.provision :shell, path: "k8s_install.sh"
    end
  end

end
