kind: Pod
apiVersion: v1
metadata:
  name: cpu-bound
  labels:
    app: cpu-bound
spec:
  containers:
    - name: cpu-bound
      image: victorbrandaoa/cpu-bound

---
kind: Service
apiVersion: v1
metadata:
  name: cpu-bound-service
spec:
  type: LoadBalancer
  selector:
    app: cpu-bound
  ports:
    - port: 8080
